wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.18
    start_time: 1710432781
    t:
      1:
      - 50
      2:
      - 50
      4: 3.8.18
      5: 0.12.11
      8:
      - 4
      - 5
